# Firebase Client Configuration (for pyrebase)
[firebase]
apiKey = "AIzaSyDpG16XfQro2hJrHOE0RCPX6fuRmUFLTcA"
authDomain = "rotary-rms.firebaseapp.com"
projectId = "rotary-rms"
storageBucket = "rotary-rms.firebasestorage.app"
messagingSenderId = "140644169838"
appId = "1:140644169838:web:8564aa43988a5a9fb78e7f"
measurementId = "G-ZMJ4GTRVNP"
databaseURL = "https://rotary-rms-default-rtdb.firebaseio.com"

# Firebase Admin SDK Configuration (Service Account JSON fields)
[firebase_admin]
type = "service_account"
project_id = "rotary-rms"
private_key_id = "575c8519dc041fa0421722553503036b73fc67d8"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDFkgIgUQjvjqq5\nJ/uzSSOA2x/oYeba2CDA4m53HOHKZkccfF0Dw5/fb9DPYEvvYqHSSyfxuFN1r5v4\nR9tIXAX8wsHCJplBMNuR9MbNhjt0KZJuzPr6X+KwQB9un9wPtxYlwC2ED9zaWEOk\nblrhEHHTB8aVePVeqxrxcuF8YQj/8tXTUKQX1ox9VmhZ3xAPcwDzBBRCw1ojoz9o\nNvclQlEgdFwZdp6vCtyJaK328dekYylKdUWbd82LwNAn3zjuEyCrN+l/BF++E+fr\nbi/DKDSCKHcAUl682hIdCXcvHpq3vTS9wV2S8c690IKrDnnfgkvCDZONyoODrmSg\n4ZxsOPu3AgMBAAECggEANJ88iL38qs2thC51mF2ZIrd6aqs00UIyix1kPb6IFyAh\nvaEUJy4CFYGTNMDZyNNU9Y2GAJhPRm+1E66T5dR41cdL0znzpMzuFpSDJPelOz3d\nXjyjdm92keoqVQ0oEFl8AScMGHofIVrT/WZVN0/peUM/bc1vUT0yqm+mRjoUKxNa\nirZJzOMdFT08Q3YzcQ1W3wz1z/pTD9xr/Ql6BAxUDfCKJ3zjFy3En8zBYyqS8P7R\nXqKGaZXvuUbAA6Sx0OFuuGM81Zsf6Bf/wdWt7iW+QoRovr0aPURY2H/RWzRk8/No\npfx9GLkdj7LhivR4gJ3niROdiXh73SozxTx3JrvL8QKBgQD+z8dBkPutc8eR7gq+\nvuiVphWGuH6Mf3ymg+YJEoN6orEh296jP7SPkkAezZEF3+36bb6oKqYC2AqVu5hc\nh4ovs2BLmoU5+SOl9fATOKBdAHcW6ujVkKO1tqWJP2L36FmuA+P06Tr3ZueucFps\nMj+euCyO450nlKI4zpX5SJCF5wKBgQDGfeOdzbqg91pbEjEu7UGJyt6+vrge0kZw\nZIaP8KRsUjYATX2pwn6gmLgoRF8M81N33LjjNGBYyCJp/kW9Vk2ycV8eZ40q/LTz\neh3xixmdUsRXfp68kFW+hjDdccG/1Cv/9oN4Hh8U+5uleDgXQJhYJyC5nkaJFnnK\nySIXLDWBsQKBgQDiPv6+2sp8sgaLLf7gaoX9CeCnI/1JJpE5EHgZqhSPuRDp7V17\nOb9KkyLXttKDktasuvDEREnu0IBlfpHD5pztyalAt8x/MxVR8FLf3jGVIiqbcKyX\no7uYRrooaN2pHOczuUSYWtX+gaJIon3G/765YPI/VR5e3HxFUDidhK6+FQKBgQCV\nV5CTYX/CrnjIPrbMpOwDnaTcBSkI35Lp62inEhrT+ULyFVuwB0s4z873VQHi/4zU\niTh+kiDPi70A3LRiEXYiBVTYznaTWlFXQ5EV9F+QU/6wCe+q1jn9QH+xjW6GQz/b\ntQETti4SnoBsDji9nfdBlCb2IZTWfheisJQ6tSOI8QKBgQCfPVqRE5+UA20P6Vap\nHrVfzH2VHq84lfSOlwPjCVSM2wLaEohg85YfjBwYMSe+sesDGKFqEpQMzDpuLRZN\nA1NRpxB/JmD6+VRvwZdiMAcSdiCw1CBJFov/V40ZNdwjO1pnwaqNujhouTPuGaDZ\nlOfB1DZCdTp+2MzSbm0epq79Lg==\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@rotary-rms.iam.gserviceaccount.com"
client_id = "108363831294412901882"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40rotary-rms.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
